// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJkN_3NR-E9hM08oEaAbOTAssLLohrncA',
    appId: '1:360303541472:web:cbe46a7d9a96d8807e6485',
    messagingSenderId: '360303541472',
    projectId: 'notes-e3915',
    authDomain: 'notes-e3915.firebaseapp.com',
    storageBucket: 'notes-e3915.appspot.com',
    measurementId: 'G-QY3GEHL9VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOtB3EcSWa7ofpFEuk89CKTM7KxolhBs',
    appId: '1:360303541472:android:b6b16bc7ce54d3657e6485',
    messagingSenderId: '360303541472',
    projectId: 'notes-e3915',
    storageBucket: 'notes-e3915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhMqRMmljNKHjQe8cRWJspNLlBrcZZr7I',
    appId: '1:360303541472:ios:57552feab082b6c97e6485',
    messagingSenderId: '360303541472',
    projectId: 'notes-e3915',
    storageBucket: 'notes-e3915.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhMqRMmljNKHjQe8cRWJspNLlBrcZZr7I',
    appId: '1:360303541472:ios:b63179239b55f5ed7e6485',
    messagingSenderId: '360303541472',
    projectId: 'notes-e3915',
    storageBucket: 'notes-e3915.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
